### ISSUE TITLE
Kel'thuzad Image File Names and Icon Names have an apostrophe in them

### ISSUE THREAD

**Issue by Zemill** [heroespatchnotes/heroes-talents#25] opened 2018-11-13 15:44 UTC
Kel'thuzad Talent Image File Names and Talent Icon picture names have an apostrophe in them

**Comment by Zemill** [comment] 2018-11-13 15:44
"icon": "storm_ui_icon_kel'thuzad_deathanddecay.png",

**Comment by MGatner** [comment] 2018-11-14 10:55
I can confirm this is how they are coming from HeroesDataParser. Definitely a little odd to have apostrophes, and not consistent with Zul’jin, Mal’Ganis, etc. I will check with @koliva8245

**Comment by MGatner** [comment] 2018-11-14 14:02
Koliva confirms this is precisely how the game files have them. I’ll keave it up to @stuaroo whether we remove apostrophes in heroes-talents

**Comment by stuaroo** [comment] 2018-11-14 17:50
I'm fine with removing apostrophes, just need to make sure we keep it consistent for future apostrophe'd heroes.  @MGatner does your automated update do much with image files at present?  I'm wondering how difficult it would be to rename images automatically.

**Comment by MGatner** [comment] 2018-11-16 02:59
I'm not currently doing anything with images. They are extracted and included in the raw portion (HeroesDataParser output) as PNGs and I manually shrunk orphea.png using TinyPNG at your suggestion, but none of the ability/talent icons have been shrunk.
If you can provide me with the parameters you use for imagemagick I can replicate the resizing and that would be a good time to remove apostrophes as well.

**Comment by stuaroo** [comment] 2018-11-17 03:07
Oh sure, previously when I was extracting images manually I was just using the basic resize command for all DDS images in the folder (`magick mogrify -resize 64x64 *.dds`) then converted to PNG (`magick mogrify -format png *.dds`).  Since the HeroesDataParser output already provides PNGs: `magick mogrify -resize 64x64 *.png`.  I didn't bother with any additional compression on these since most of the 64x64 icons ended up being ~10 KB, but if we think they can be even smaller I'm open to options!

**Comment by MGatner** [comment] 2018-11-29 17:34
Fixed by https://github.com/heroespatchnotes/heroes-talents/pull/28

**Closed by MGatner** 2018-11-29 17:34 UTC
